### ISSUE TITLE
Privly icon scrolls with window

### ISSUE THREAD

**Issue by bhaveshgoyal** [privly/privly-chrome#103] opened 2015-03-07 21:54 UTC
When privly is in injecting state and facebook chat window is opened, the icon appears on its correct place, in the input box. But when window is scrolled the 'privly icon doesnt stays fixed in the chat window but scrolls up as the window moves down. This may have something to do with the position of the icon set to 'fixed' may be...

**Comment by smcgregor** [comment] 2015-03-07 23:14
Duplicate of #90

**Closed by smcgregor** 2015-03-07 23:14 UTC
