### ISSUE TITLE
Seamless posting

### ISSUE THREAD

**Issue by fullvlad** [privly/privly-chrome#70] opened 2014-11-16 01:27 UTC
The user wants to post content via a form and they don't want to think about using Privly. It should "just work". This requires hijacking the appropriate posting forms. There are several cases we should examine:

1. The host page's form submits when the user hits the "enter" key.
2. The host page's form has a "submit" or a "send" button.

Both of these cases need to be supported in seamless posting and pose very different design constraints. More problematically, you can't tell which case the form falls into in the code. 

To compensate for both cases, the following activity could be used, under the assumption that the user wants to post with Privly:

1. When the user clicks on a text area, the extension automatically creates a new link and drops it into the host page. This link is now associated with the content the user is eventually going to write into the form.
2. The browser extension then puts an iframe into the context of the host page that is associated with the new link. When the user types into the iframe, it updates the content stored at the content server.
3. When the user hits the "enter" key, or the "submit" button on the web page, the link is submitted and the iframe disappears.

**Comment by SummerWish** [comment] 2015-03-06 11:50
Good idea, but would it be too frequent of sending requests to update stored content?

**Comment by SummerWish** [comment] 2015-03-06 13:32
Hello, I extended seemless posting idea as the following.

[A short demo](https://breeswish.org/file/privly-20140306.mp4)

General design direction:

- When using priv.ly in textarea, the whole content would be encrypted with a default life time (can be changed in config, or a drop down).
- If users want to add plain messages, they can use priv.ly extension button to generate a link.

Details:

- When a textarea get focus, there would be a priv.ly control icon (the same as present), indicates whether this textarea is in "private mode".
- priv.ly control icon (and the textarea) has three status: Public Mode, Private Mode, Permanent Private Mode, can be switched by clicking.
  - Public Mode (default): priv.ly is not working. Textarea works as original. 
  - Private Mode: priv.ly is working. if the page is refreshed (more accurately, the textarea is re-generated), the textarea will return to Public Mode.
  - Permanent Private Mode (remember using private mode for this textarea): this textarea will be always in Private Mode after refresh. (use XPath?)
- there could be other stuff help indicate the current status. for example, the background of the textarea could become green when in (Permanent) Private Mode.
- users can drag images to the textbox when it is in (Permanent) Private Mode. priv.ly treat it as data URI inlined images. The whole message to encrypt is an HTML document.

Use cases:

1. User want to publish public messages
   just don't do anything. the default status of the textarea is Public Mode. If it is in other two mode, just click the icon once or twice.

2. User want to send a piece of private message
   Click the icon to switch it to (Permanent) Private Mode, write messages, then hit control/command + enter to submit. (for what happens when submitting, see technical details section below)

3. User want to send private message in Facebook Chat for the current session
   The same as case 2. Since the textarea wouldn't be regenerated, both Private Mode and Permanent Mode is OK.

4. User want to send one private message in Facebook Chat
   After submitting a private message, click icon to return to Public Mode.

5. User want to send private message for all Facebook Chat sessions
   Switch to permanent private mode. How to correctly generate feature Xpath that meets user's need should be discussed further. A simple CSS selector like Xpath from document root might work in most of the cases, but not all.

6. User want to embed image in public mode
   Impossible.

7. User want to embed image in Private mode
   Drag image to the "private mode" textarea. (Like GitHub)

8. User want to post private messages mixed with images and texts
   Write text, then drag image.

9. User want to mix public and private message in one message
   Switch textarea to public mode if it isn't in. Then click extension button to popup a writing window which will generate a privly link finally and be automatically pasted to the textarea (similar to current).

10. User want to generate a privly link for being used in other applications
   click extension button.

11. User want to specify a life time for the private message
   Provide a drop down to change life time when hover on control icon.

Technical details:

1. What happens when hitting ctrl/command + enter or enter in Private Mode?
   
   - On entering private mode:
     - ACTION_INIT

   - On blur:
     - ACTION_UPDATE

   - On Keypress:
     - ACTION_UPDATE (with throttle)

   - On `Enter` or `Ctrl,Command + Enter`:
     - insert new line
     - ACTION_UPDATE, when complete: forward the event to original textarea

   Actions:

   - ACTION_INIT:
     - Disable submit button if there is one
     - create a new link
     - insert the new link to textarea/contenteditable div
     - enable submit button
     - onComplete callback

   - ACTION_UPDATE:
     - Disable submit button if there is one
     - update stored content
     - enable submit button
     - onComplete callback

   Expected behaviour: (\* = the same with original behavior)

   - stackoverflow:
     enter or ctrl+enter: insert new line (\*)

   - Facebook status:
     enter: insert new line (\*)
     ctrl+enter: publish (\*)

   - Facebook chat:
     enter: publish (\*)
     ctrl+enter: insert new line

2. Content editable or ACE/CodeMirror-like stuff?
   
   To be discussed

3. What happens when switching modes (if there are contents) ?

   To be discussed

**Comment by smcgregor** [comment] 2015-03-06 17:17
First thoughts:

* No encrypting whole HTML documents, only their contents. Sandboxing is pretty cool, but its attack surface is still too big.
* You have too many modes/options. I think it would be better to have a toggle for "on" and "off". If it is on, then it should be on for all elements on the domain with the same xpath. We could then also publish a default setting for things like Twitter DMs, FB chats, and gchats.
* When typing into the seamless form, keys should have the same interpretation as if you were typing them into the host page's form. This will require some clever hackery.

**Comment by SummerWish** [comment] 2015-03-08 03:41
@smcgregor 

For the third point, I think passing keyboard enter events to inherit potential submiting features (like Facebook Chat) is enough. Other keyboard events might be pretty hard to deal with.

For example, inputing `@x` in Twitter will popup an at list, while replacing original `@x` text node to something like `<a href="/x">...</a>`, which means it won't work while original `<div contenteditable>` doesn't contain such text nodes. In addition, even though we successfully hacked this that make it work in browsers, it still won't work in server side because the server only receives URI links. Besides, this may leak data to the host site for as far as I know some websites collect all keyboard events.

**Comment by smcgregor** [comment] 2015-03-08 20:31
Regarding the third point: Absolutely. I just had control characters in mind, thanks for clarifying.

**Comment by SummerWish** [comment] 2015-03-09 02:28
@smcgregor  LOL, sounds good

**Comment by smcgregor** [comment] 2015-09-25 21:14
This has landed in develop

**Closed by smcgregor** 2015-09-25 21:14 UTC
Labels: Feature Request, Major, Needs Work, Project, UX
